version: '3.7'

services:
  fn:
    # env_file:
    #   - ./fn/.env.local
    build:
      context: ./fn
      dockerfile: dev.Dockerfile
      args:
        - APP=/app
    command: dev
    ports:
      - 5001:5001
    volumes:
      - ./fn:/app