version: '3.7'

services:
  fn:
    env_file:
      - ./fn/.env.local
    build: 
      context: ./fn
      dockerfile: dev.Dockerfile
      args:
        - APP=/app
    command: dev
    volumes:
      - ./fn:/app