services:
  kratos-migrate:
    image: oryd/kratos:v0.13.0
    environment:
      - DSN=postgres://kratos:secret@kratos-postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./kratos/config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    depends_on:
      - kratos-postgres

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.13.0
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:secret@kratos-postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    expose:
      - 4433 # Public port
      - 4434 # Admin port
    volumes:
      - type: bind
        source: ./kratos/config
        target: /etc/config/kratos

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"

  kratos-postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    volumes:
      - "./.data/kratos-postgres:/var/lib/postgresql/data:rw"
    ports:
      - "54322:5432"


  heimdall:
    build:
      context: ./heimdall
      dockerfile: Dockerfile
      args:
        - ENV=dev
        - PUBLIC_ROOT_URL=http://localhost:8000
    volumes:
      - ./heimdall/config:/heimdall/conf
      - ./heimdall/config/keys/dev/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    depends_on:
      - kratos
    ports:
      - 8000:4455
      - 4457:4457
    command: -c /heimdall/conf/dev.config.yaml serve proxy
    environment:
      - RULES_FILE_PATH=/heimdall/conf/rules/dev.rules.yaml
      - KEYSTORE_FILE_PATH=/heimdall/conf/keys/dev/keystore.pem
    extra_hosts:
      - "host.docker.internal:host-gateway"

  hasura-postgres:
    restart: unless-stopped
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "./.data/hasura-postgres:/var/lib/postgresql/data:rw"
    ports:
      - "54321:5432"

  hasura:
    restart: unless-stopped
    env_file:
      - ./hasura/.env
    depends_on:
      - hasura-postgres
    build:
      context: hasura
      dockerfile: Dockerfile
    volumes:
      - ./hasura:/project


  fn:
    build:
      context: ./fn
      dockerfile: dev.Dockerfile
      args:
        - APP=/app
    command: dev
    environment:
      - JWKS_ENDPOINT=http://heimdall:4457/.well-known/jwks
      - KRATOS_DOMAIN=kratos:4433
      - HASURA_DOMAIN=hasura:8080
    ports:
      - 8001:8001
    volumes:
      - ./fn:/app
