services:
  auth-redis:
    env_file:
      - .env.dev
    extends:
      file: compose.yaml
      service: auth-redis

  auth:
    env_file:
      - .env.dev
    extends:
      file: compose.yaml
      service: auth
    # ports:
    #   - "6499:6499"
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000
      - HASURA_ENDPOINT=http://hasura:8080
    volumes:
      - ./auth:/app
    command: ["run", "dev"]

  hasura-postgres:
    env_file:
      - .env.dev
    extends:
      file: compose.yaml
      service: hasura-postgres
    ports:
      - "5432:5432"
    volumes:
      - "./.data/hasura-postgres:/var/lib/postgresql/data:rw"

  hasura:
    env_file:
      - .env.dev
    extends:
      file: compose.yaml
      service: hasura
    environment:
      # - HASURA_GRAPHQL_METADATA_DIR='' # "/project/metadata"
      # - HASURA_GRAPHQL_MIGRATIONS_DIR='' # "/project/migrations"
      - HASURA_GRAPHQL_CORS_DOMAIN=http://localhost:3000,http://localhost:9695
      - DEFANG_FN_ENDPOINT=http://api:3003
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@hasura-postgres:5432/postgres
      - HASURA_GRAPHQL_JWT_SECRET={"jwk_url":"http://auth:3001/.well-known/jwks.json","claims_namespace_path":"$.properties.hasura"}
      - HASURA_GRAPHQL_ADMIN_SECRET
    volumes:
      - ./hasura:/project

  api:
    env_file:
      - .env.dev
    extends:
      file: compose.yaml
      service: api
    command: run dev
    ports:
      - "6499:6499"
    environment:
      - AUTH_ENDPOINT=http://auth:3001
      - HASURA_ENDPOINT=http://hasura:8080
      - PUBLIC_ROOT_URL=http://localhost:3000
      - STRIPE_SECRET_KEY
    volumes:
      - ./api:/app
