name: portal-staging

services:
  auth-redis:
    extends:
      file: compose.yaml
      service: auth-redis

  auth:
    extends:
      file: compose.yaml
      service: auth
    domainname: auth.staging.defang.dev
    x-defang-dns-role: arn:aws:iam::258338292852:role/dnsadmin-1996833

  hasura-postgres:
    extends:
      file: compose.yaml
      service: hasura-postgres

  hasura:
    extends:
      file: compose.yaml
      service: hasura
    environment:
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    domainname: graphql.staging.defang.dev
    x-defang-dns-role: arn:aws:iam::258338292852:role/dnsadmin-1996833


  api:
    extends:
      file: compose.yaml
      service: api
    domainname: api.staging.defang.dev
    x-defang-dns-role: arn:aws:iam::258338292852:role/dnsadmin-1996833

  web:
    extends:
      file: compose.yaml
      service: web
    domainname: portal.staging.defang.dev
    x-defang-dns-role: arn:aws:iam::258338292852:role/dnsadmin-1996833
