services:
  auth-redis:
    image: redis:6.2
    x-defang-redis: true
    ports:
      - mode: host
        target: 6379
        published: 6379

  auth:
    domainname: auth.${DOMAIN_NAME}
    build:
      context: ./auth
    ports:
      - mode: ingress
        target: 3001
        published: 3001
    environment:
      - PORT=3001
      - REDIS_URL=redis://auth-redis:6379
      # DEFANG CONFIG
      - ALLOWED_ORIGINS=https://${DOMAIN_NAME},https://portal.${DOMAIN_NAME}
      - HASURA_ENDPOINT=https://graphql.${DOMAIN_NAME}
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - HASURA_GRAPHQL_ADMIN_SECRET
      - SEGMENT_WRITE_KEY
      - GITLAB_CLIENT_ID
      - GITLAB_CLIENT_SECRET
    depends_on:
      - auth-redis

  hasura-postgres:
    image: postgres:16
    x-defang-postgres: true
    ports:
      - mode: host
        target: 5432
    environment:
      POSTGRES_PASSWORD:

  hasura:
    domainname: graphql.${DOMAIN_NAME}
    restart: unless-stopped
    build:
      context: hasura
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 8080
        published: 3002
    environment:
      - HASURA_GRAPHQL_ENABLE_CONSOLE=false
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES=startup,http-log,webhook-log,websocket-log,query-log
      - HASURA_GRAPHQL_UNAUTHORIZED_ROLE=public
      - HASURA_GRAPHQL_INFER_FUNCTION_PERMISSIONS=false
      - HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS=true
      - HASURA_GRAPHQL_EXPERIMENTAL_FEATURES=naming_convention
      # DEFANG CONFIG
      - HASURA_GRAPHQL_CORS_DOMAIN=https://${DOMAIN_NAME},https://*.${DOMAIN_NAME}
      - DEFANG_FABRIC=https://fabric-prod1.defang.dev
      - DEFANG_FN_ENDPOINT=https://api.${DOMAIN_NAME}
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@hasura-postgres:5432/postgres
      - HASURA_GRAPHQL_JWT_SECRET={"jwk_url":"https://auth.${DOMAIN_NAME}/.well-known/jwks.json","claims_namespace_path":"$.properties.hasura"}
      - HASURA_GRAPHQL_ADMIN_SECRET
      - DEFANG_API_SECRET
      - DEFANG_FABRIC_SHARED_SECRET
      # Trigger action to investigate weird DOMAIN_NAME interpolation
    depends_on:
      - hasura-postgres
      - auth

  api:
    domainname: api.${DOMAIN_NAME}
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - PORT=3003
      # DEFANG CONFIG
      - AUTH_ENDPOINT=https://auth.${DOMAIN_NAME}
      - HASURA_ENDPOINT=https://graphql.${DOMAIN_NAME}
      - PUBLIC_ROOT_URL=https://portal.${DOMAIN_NAME}
      - HASURA_GRAPHQL_ADMIN_SECRET
      - STRIPE_SECRET_KEY
      - STRIPE_WEBHOOK_SECRET
      - SEGMENT_WRITE_KEY
      - DEFANG_API_SECRET
    ports:
      - mode: ingress
        target: 3003
        published: 3003

  web:
    domainname: portal.${DOMAIN_NAME}
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_AUTH_URL=https://auth.${DOMAIN_NAME}
        - NEXT_PUBLIC_GRAPHQL_URL=https://graphql.${DOMAIN_NAME}/v1/graphql
        - NEXT_PUBLIC_FABRIC=${NEXT_PUBLIC_FABRIC}
        - NEXT_PUBLIC_PRICE_IDS
        # DEFANG CONFIG
        - NEXT_PUBLIC_SEGMENT_WRITE_KEY
        - NEXT_PUBLIC_VERSION
    ports:
      - mode: ingress
        target: 3000
        published: 3000
