version: '3'

services:
  heimdall:
    build: 
      context: ./heimdall
      dockerfile: Dockerfile
      args:
        - ENV=dev
        - PUBLIC_ROOT_URL=http://localhost:5000
    volumes:
      - ./heimdall/config:/heimdall/conf
      - ./heimdall/config/keys/dev/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    depends_on:
      - kratos
    ports:
      - 5000:4455
      - 4457:4457
    command: -c /heimdall/conf/dev.config.yaml serve proxy
    environment:
      - RULES_FILE_PATH=/heimdall/conf/rules/dev.rules.yaml
      - KEYSTORE_FILE_PATH=/heimdall/conf/keys/dev/keystore.pem
    extra_hosts:
      - "host.docker.internal:host-gateway"
