-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION generate_unique_tenant(p_email TEXT)
-- RETURNS TEXT AS $$
-- DECLARE
--   base TEXT;
--   candidate TEXT;
--   counter INT := 0;
--
--   -- Array of 50 three-letter words
--   words TEXT[] := ARRAY[
--     'ace', 'act', 'add', 'age', 'aid', 'aim', 'air', 'ale', 'all', 'ant',
--     'ape', 'arm', 'art', 'ash', 'ask', 'bag', 'bar', 'bat', 'bid', 'bit',
--     'cap', 'cat', 'cow', 'cup', 'dig', 'dog', 'dry', 'eat', 'fit', 'fun',
--     'gap', 'gem', 'get', 'hit', 'ice', 'jar', 'joy', 'key', 'lap', 'log',
--     'man', 'mix', 'new', 'nod', 'oil', 'pop', 'rob', 'run', 'sky', 'sun'
--   ];
--
--   -- Temporary array for shuffling
--   shuffled_words TEXT[];
--   i INT;
--   j INT;
--   temp TEXT;
-- BEGIN
--   IF p_email IS NULL OR length(trim(p_email)) = 0 THEN
--     -- Shuffle 'words' via a simple Fisher-Yates shuffle
--     shuffled_words := words;
--     FOR i IN 1..array_length(shuffled_words, 1) LOOP
--       j := floor(random() * (array_length(shuffled_words, 1) - i + 1))::int + i;
--       IF j != i THEN
--         temp := shuffled_words[i];
--         shuffled_words[i] := shuffled_words[j];
--         shuffled_words[j] := temp;
--       END IF;
--     END LOOP;
--
--     -- Concatenate the first three shuffled words
--     base := shuffled_words[1] || shuffled_words[2] || shuffled_words[3];
--   ELSE
--     -- Take the local part up to 12 characters, remove non-alphanumeric
--     base := substring(
--       regexp_replace(lower(split_part(p_email, '@', 1)), '[^a-z0-9]', '', 'g')
--       FROM 1 FOR 12
--     );
--   END IF;
--
--   candidate := base;
--
--   -- Loop until tenant is unique
--   WHILE EXISTS (SELECT 1 FROM users WHERE tenant = candidate) LOOP
--     counter := counter + 1;
--     candidate := base || counter;
--   END LOOP;
--
--   RETURN candidate;
-- END;
-- $$ LANGUAGE plpgsql;
