version: "1alpha2"
rules:
  - id: "kratos:public-api"
    match:
      url: "http://localhost:8000/svc/kratos/<**>"
    forward_to:
      host: kratos:4433
      rewrite:
        scheme: http
        strip_path_prefix: /svc/kratos
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    execute:
      - authenticator: noop
      - authorizer: allow_all_requests
      - unifier: noop

  - id: "hasura:public-api"
    match:
      url: "http://localhost:8000/svc/hasura/<**>"
    forward_to:
      host: hasura:8080
      rewrite:
        scheme: http
        strip_path_prefix: /svc/hasura
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    execute:
      - authenticator: kratos_session_cookie
      - authenticator: noop
      - authorizer: allow_all_requests
      - unifier: create_jwt

  - id: "fn:public-api"
    match:
      url: "http://localhost:8000/svc/fn/<**>"
    forward_to:
      host: fn:5001
      rewrite:
        scheme: http
        strip_path_prefix: /svc/fn
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    execute:
      - authenticator: kratos_session_cookie
      - authenticator: noop
      - authorizer: allow_all_requests
      - unifier: create_jwt

  - id: "nextjs:public"
    match:
      url: "http://localhost:8000<**>"
    forward_to:
      host: host.docker.internal:3000
      rewrite:
        scheme: http
    methods:
      - HEAD
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    execute:
      - authenticator: noop
      - authorizer: allow_all_requests
      - unifier: noop
