type Mutation {
  createStripeCheckoutSession(
    input: CreateStripeCheckoutSessionInput!
  ): CreateStripePortalSessionOutput
}

type Mutation {
  createStripePortalSession: CreateStripePortalSessionOutput
}

type Mutation {
  createStripeSecret: CreateStripeSecretOutput
}

type Mutation {
  deleteAccount: DeleteAccountOutput
}

input CreateStripeCheckoutSessionInput {
  priceId: String!
}

type DeleteAccountOutput {
  message: String!
}

type CreateStripeSecretOutput {
  secret: String!
}

type CreateStripePortalSessionOutput {
  url: String!
}

type CreateStripeCheckoutSessionOutput {
  url: String!
}

