type Mutation {
  createStripeCheckoutSession(
    input: CreateStripeCheckoutSessionInput!
  ): CreateStripePortalSessionOutput
}

type Mutation {
  createStripePortalSession: CreateStripePortalSessionOutput
}

type Mutation {
  createStripeSecret: CreateStripeSecretOutput
}

type Mutation {
  deleteUser: DeleteUserOutput
}

type Mutation {
  initiateTenantDeletion(
    tenantId: uuid!
  ): InitiateTenantDeletionOutput
}

type Mutation {
  resolveAwsMarketplaceCustomer(
    input: ResolveAwsMarketplaceCustomerInput!
  ): ResolveAwsMarketplaceCustomerOutput
}

input CreateStripeCheckoutSessionInput {
  priceId: String!
}

input ResolveAwsMarketplaceCustomerInput {
  registrationToken: String!
}

type DeleteUserOutput {
  message: String!
}

type CreateStripeSecretOutput {
  secret: String!
}

type CreateStripePortalSessionOutput {
  url: String!
}

type CreateStripeCheckoutSessionOutput {
  url: String!
}

type InitiateTenantDeletionOutput {
  message: String!
}

type ResolveAwsMarketplaceCustomerOutput {
  customerAWSAccountId: String!
  customerIdentifier: String!
  productCode: String!
}

