name: Deploy to AWS
description: Deploy application to AWS environment

inputs:
  aws_account_id:
    description: "AWS Account ID"
    required: true
  aws_region:
    description: "AWS Region"
    required: false
    default: "us-west-2"
  project_name:
    description: "Project name"
    required: true
  domain_name:
    description: "Domain Name"
    required: true
  github_client_id:
    description: "GitHub Client ID"
    required: true
  github_client_secret:
    description: "GitHub Client Secret"
    required: true
  hasura_graphql_admin_secret:
    description: "Hasura GraphQL Admin Secret"
    required: true
  next_public_segment_write_key:
    description: "Next Public Segment Write Key"
    required: true
  next_public_stripe_pricing_table_id:
    description: "Next Public Stripe Pricing Table ID"
    required: true
  next_public_stripe_publishable_key:
    description: "Next Public Stripe Publishable Key"
    required: true
  next_public_version:
    description: "Next Public Version"
    required: true
  postgres_password:
    description: "Postgres Password"
    required: true
  segment_write_key:
    description: "Segment Write Key"
    required: true
  stripe_secret_key:
    description: "Stripe Secret Key"
    required: true
  defang_api_secret:
    description: "Defang API Secret"
    required: true
  next_public_fabric:
    description: "Next Public Fabric"
    required: false
    default: ""
  # Next Public Price IDs is a json object that looks like this (Tier, Timeframe, Price ID):
  # {"PERSONAL":{"MONTHLY":"price_1QKRCqGzPK2DOcG5PHH1e9TY"},"PRO":{"MONTHLY":"price_1QKRDsGzPK2DOcG5Didy72JY"}}
  next_public_price_ids:
    description: "Next Public Price IDs"
    required: true
  stripe_webhook_secret:
    description: "Stripe Webhook Secret"
    required: true
  stripe_default_price_id:
    description: "Stripe Default Price ID"
    required: true
  compose_file:
    description: "Compose file"
    required: true
  mode:
    description: "Deployment mode (development | staging | production)"
    default: development
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials for CI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
        role-to-assume: arn:aws:iam::488659951590:role/ci-role-d4fe904 # ciRoleArn from defang-io/infrastructure stack
    - name: Configure AWS Credentials for Corp Website Account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws_region }}
        role-chaining: true
        role-duration-seconds: 1200
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/admin
    - name: Create dotenv file
      shell: bash
      run: |
        echo "DOMAIN_NAME=${{ inputs.domain_name }}" >> .env
        echo "NEXT_PUBLIC_FABRIC=${{ inputs.next_public_fabric }}" >> .env
        echo "NEXT_PUBLIC_SEGMENT_WRITE_KEY=${{ inputs.next_public_segment_write_key }}" >> .env
        echo "NEXT_PUBLIC_VERSION=${{ inputs.next_public_version }}" >> .env
        echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${{ inputs.next_public_stripe_publishable_key }}" >> .env
        echo "NEXT_PUBLIC_STRIPE_PRICING_TABLE_ID=${{ inputs.next_public_stripe_pricing_table_id }}" >> .env
        echo 'NEXT_PUBLIC_PRICE_IDS=${{ inputs.next_public_price_ids }}' >> .env
        cat .env
    - name: Deploy
      uses: DefangLabs/defang-github-action@v1.2.0
      with:
        mode: ${{ inputs.mode }}
        compose-files: ${{ inputs.compose_file }}
        config-env-vars: DOMAIN_NAME GITHUB_CLIENT_ID GITHUB_CLIENT_SECRET GITLAB_CLIENT_ID GITLAB_CLIENT_SECRET HASURA_GRAPHQL_ADMIN_SECRET NEXT_PUBLIC_SEGMENT_WRITE_KEY NEXT_PUBLIC_STRIPE_PRICING_TABLE_ID NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY NEXT_PUBLIC_VERSION POSTGRES_PASSWORD SEGMENT_WRITE_KEY STRIPE_SECRET_KEY DEFANG_API_SECRET STRIPE_DEFAULT_PRICE_ID STRIPE_WEBHOOK_SECRET DEFANG_FABRIC_SHARED_SECRET
      env:
        DEFANG_PROVIDER: aws
        DOMAIN_NAME: ${{ inputs.domain_name }}
        GITHUB_CLIENT_ID: ${{ inputs.github_client_id }}
        GITHUB_CLIENT_SECRET: ${{ inputs.github_client_secret }}
        GITLAB_CLIENT_ID: ${{ inputs.gitlab_client_id }}
        GITLAB_CLIENT_SECRET: ${{ inputs.gitlab_client_secret }}
        HASURA_GRAPHQL_ADMIN_SECRET: ${{ inputs.hasura_graphql_admin_secret }}
        NEXT_PUBLIC_SEGMENT_WRITE_KEY: ${{ inputs.next_public_segment_write_key }}
        NEXT_PUBLIC_STRIPE_PRICING_TABLE_ID: ${{ inputs.next_public_stripe_pricing_table_id }}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ inputs.next_public_stripe_publishable_key }}
        NEXT_PUBLIC_VERSION: ${{ inputs.next_public_version }}
        POSTGRES_PASSWORD: ${{ inputs.postgres_password }}
        SEGMENT_WRITE_KEY: ${{ inputs.segment_write_key }}
        STRIPE_SECRET_KEY: ${{ inputs.stripe_secret_key }}
        NEXT_PUBLIC_FABRIC: ${{ inputs.next_public_fabric }}
        DEFANG_API_SECRET: ${{ inputs.defang_api_secret }}
        DEFANG_FABRIC_SHARED_SECRET: ${{ inputs.defang_fabric_shared_secret }}
        STRIPE_WEBHOOK_SECRET: ${{ inputs.stripe_webhook_secret }}
        STRIPE_DEFAULT_PRICE_ID: ${{ inputs.stripe_default_price_id }}
