- id: "ory:kratos:public"
  upstream:
    preserve_host: true
    url: "http://kratos:4433"
    # strip_path: /.ory/kratos/public
  match:
    # url: "http://127.0.0.1:4433/.ory/kratos/public/<**>"
    url: "http://127.0.0.1:4433/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: "hasura:graphql:public"
  upstream:
    preserve_host: true
    url: "http://hasura:8080"
  match:
    url: "http://localhost:5000/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
    


- id: "fn:rest:public"
  upstream:
    preserve_host: true
    url: "http://fn:5001"
  match:
    url: "http://localhost:5001/<**>"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
    
