log:
  level: trace
  format: json
  leak_sensitive_values: true

serve:
  api:
    port: 4456
  proxy:
    port: 4455
    cors:
      enabled: true
      allowed_origins:
        - "http://localhost:5000"
        - "http://localhost:9695"
        - "http://localhost:9693"
      allowed_methods:
        - POST
        - GET
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - "*"
        # - Authorization
        # - Content-Type
      exposed_headers:
        - Content-Type
      allow_credentials: true
      debug: true

errors:
  fallback:
    - json

  handlers:
    redirect:
      enabled: true
      config:
        to: http://127.0.0.1:3000/auth
        when:
          - error:
              - unauthorized
              - forbidden
            request:
              header:
                accept:
                  - text/html
    json:
      enabled: true
      config:
        verbose: true

access_rules:
  matching_strategy: regexp
  repositories:
    - file:///etc/config/oathkeeper/access-rules.yml

authenticators:
  anonymous:
    enabled: true
    config:
      subject: public

  noop:
    enabled: true

  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      only:
        - ory_kratos_session

  bearer_token:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      preserve_query: true
      token_from:
        query_parameter: auth-token

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true

mutators:
  noop:
    enabled: true

  id_token:
    enabled: true
    config:
      issuer_url: http://localhost:5000/.ory/kratos/public
      jwks_url: file:///etc/config/oathkeeper/id_token.jwks.json
      claims: |
        {
          {{- $identity := .Extra.identity -}}
          {{ if $identity -}}
          "https://hasura.io/jwt/claims": "{\"x-hasura-default-role\": \"user\",\"x-hasura-allowed-roles\": [\"user\"],\"x-hasura-user-id\": \"{{ $identity.id }}\"}"
          {{- end }}
        }
