version: "3.7"

services:
  hasura-postgres:
    restart: unless-stopped
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "./.data/hasura-postgres:/var/lib/postgresql/data:rw"

  hasura:
    restart: unless-stopped
    env_file:
      - ./hasura/.env
    depends_on:
      - hasura-postgres
    build:
      context: hasura
      dockerfile: Dockerfile
    volumes:
      - ./hasura:/project
