log:
  level: debug

serve:
  proxy:
    trusted_proxies:
      - 0.0.0.0/0

signer:
  key_store:
    path: ${KEYSTORE_FILE_PATH:="/heimdall/conf/keys/dev/keystore.pem"}

rules:
  mechanisms:
    authenticators:
      - id: anonymous_authenticator
        type: anonymous
      - id: noop
        type: noop
      - id: kratos_session_cookie
        type: generic
        config:
          identity_info_endpoint: http://kratos:4433/sessions/whoami
          authentication_data_source:
            - cookie: ory_kratos_session
          forward_cookies:
            - ory_kratos_session
          subject:
            id: "identity.id"
          cache_ttl: 5m
          session_lifespan:
            active: active
            issued_at: issued_at
            not_before: authenticated_at
            not_after: expires_at
            time_format: "2006-01-02T15:04:05.999999Z07"
            validity_leeway: 10s
    authorizers:
      - id: deny_all_requests
        type: deny
      - id: allow_all_requests
        type: allow
    unifiers:
      - id: create_jwt
        type: jwt
        config:
          ttl: 1m
          claims: |
            {
              {{ with .Subject.Attributes.identity -}}
              "https://hasura.io/jwt/claims": {
                "x-hasura-default-role": "user",
                "x-hasura-allowed-roles": ["user"],
                "x-hasura-user-id": "{{ .id }}"
              }
              {{- with .traits -}}
                {{- with .github -}}
                  {{- if .username -}}
                    ,
                    "https://defang.io/jwt/claims": {
                      "github-username": "{{ .username }}"
                    }
                  {{- end -}}
                {{- end -}}
              {{- end -}}
              {{- else -}}
              "https://hasura.io/jwt/claims": {
                "x-hasura-default-role": "public",
                "x-hasura-allowed-roles": ["public"],
                "x-hasura-user-id": "anonymous"
              }
              {{- end }}
            }
      - id: noop
        type: noop

  default:
    methods:
      - GET
      - POST
    execute:
      - authenticator: anonymous_authenticator
      - authorizer: deny_all_requests
      - unifier: create_jwt

  providers:
    file_system:
      src: ${RULES_FILE_PATH:="/heimdall/conf/dev.rules.yaml"}
      watch: true
