name: Pulumi Up Portal

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

permissions:
  contents: read
  id-token: write # for defang login

jobs:
  up:
    name: Pulumi Up
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' # only runs on push/merge to main branch
    steps:
      - name: Log into Defang prod
        run: |
          . <(curl -s https://raw.githubusercontent.com/DefangLabs/defang/main/src/bin/install.sh)
          defang --debug login

      - uses: actions/checkout@v4
        with:
          persist-credentials: false # we don't expect to do any pushes from this workflow

      - uses: ./.github/actions/npm-ci
        with:
          cache-dependency-path: pulumi/package-lock.json
          working-directory: pulumi

      - name: Run pulumi up (production)
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: defang-io/production
          work-dir: ./pulumi
        env:
          AIVEN_TOKEN: ${{ secrets.AIVEN_TOKEN }} # for connecting to Aiven
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # for downloading pulumi plugins
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          # PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
